server:
  port: 8005
  servlet:
    context-path: /authentication/api

# Eureka client configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include=*:

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/pizzeria?createDatabaseIfNotExist=true
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

#Logging level
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  org:
    springframework:
      security:
        web:
          '*': debug
    com:
      netflix:
        eureka: INFO
        discovery: INFO