server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-api
          uri: lb://BOOK-API
          predicates:
            - Path=/book/api/books/**
        - id: rating-api
          uri: lb://rating-api
          predicates:
            - Path=/rating/api/ratings/**
        - id: authentication-api
          uri: lb://authentication-api
          predicates:
            - Path=/authentication/api/**

management:
  endpoints:
    web:
      exposure:
        include: "*"