server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-api
          uri: lb://AUTHENTICATION-API
          predicates:
            - Path=/authentication/api/**
        #- id: book-api
          #uri: lb://BOOK-API
          #predicates:
            #- Path=/book/api/books/**
          #filter: authenticationFilter
        - id: rating-api
          uri: lb://RATING-API
          predicates:
            - Path=/rating/api/ratings/**

management:
  endpoints:
    web:
      exposure:
        include: "*"